workspace: true

default:
  environment:
    DATABASE_HOSTNAME: db
    DATABASE_USERNAME: hypebid
    DATABASE_PASSWORD: drowssap
    RAILS_ENV: test

stages:
  - build
  - test

jobs:
  - name: build:prepare
    stage: build
    image: tuant/ruby:latest
    script:
      - gem install bundler
      - bundle _2.1.4_ install --path vendor/bundle
      - mkdir -p ./.sun-ci-reports
    cache:
      - key: vendor_$CI_BRANCH
        paths:
          - vendor/bundle
        expires_in: 3 days
    only:
      events:
        - pull_request

  # - name: test:bundle_audit
  #   stage: test
  #   image: tuant/ruby:latest
  #   before_script:
  #     - bundle _2.1.4_ install --path vendor/bundle
  #   script:
  #     - bundle-audit check --update | tee .sun-ci-reports/bundle-audit.txt
  #   artifacts:
  #     paths:
  #       - ./.sun-ci-reports/bundle-audit.txt

  # - name: test:brakeman
  #   stage: test
  #   image: tuant/ruby:latest
  #   before_script:
  #     - bundle _2.1.4_ install --path vendor/bundle
  #   script:
  #     - bundle exec brakeman -o .sun-ci-reports/brakeman.html
  #   artifacts:
  #     paths:
  #       - ./.sun-ci-reports/brakeman.html

  # - name: test:rubocop
  #   stage: test
  #   image: tuant/ruby:latest
  #   before_script:
  #     - bundle _2.1.4_ install --path vendor/bundle
  #     - printenv
  #   script:
  #     - bundle exec rubocop --require rubocop/formatter/checkstyle_formatter \
  #       --format RuboCop::Formatter::CheckstyleFormatter --no-color \
  #       --format html -o .sun-ci-reports/rubocop.html app/ lib/ db/migrate/ config/
  #   artifacts:
  #     paths:
  #       - ./.sun-ci-reports/rubocop.yml

  - name: test:rspec
    stage: test
    image: tuant/ruby:latest
    services:
      - image: mysql:5.7
        name: db
        environment:
          MYSQL_DATABASE: hypebid_test
          MYSQL_USER: hypebid
          MYSQL_PASSWORD: drowssap
          MYSQL_ROOT_PASSWORD: root
    before_script:
      - bundle _2.1.4_ install --path vendor/bundle
      - bundle exec rake db:schema:load
    script:
      - printenv
      - bundle _2.1.4_ exec rspec spec
